“Listo para revisión”.[IS-23-24]
Artur-Sultanov/FISH pull request #3
Opened 2024-02-14 16:19 UTC by Artur-Sultanov

2024-02-15 08:00 UTC, JJ commented
1. Por favor, pon un título al PR.
2. Además de copiar y pegar la lista de comprobación, hay que seguirla, comprobar si es cierto lo que se pregunta, y marcarlo en su caso. Si no es cierto, conviene que se examine por qué y se mejore la entrega, porque suelen ser una guía de la calidad de la misma.

2024-02-15 08:04 UTC, JJ requested changes
Por favor, recuerda seguir la lista de comprobación, tras la lectura atenta de la descripción de este nivel y lo que se busca una entrega.
Recuerda que un milestone (y el resto, como las historias de usuario, que *no* has entregado) son documentos técnicos para guiar el desarrollo. ¿Crees que una frase que diga "el primer milestone es un modelo del problema" ayuda a un equipo de programación a saber qué tienen que entregar como tal?

2024-02-15 08:04 UTC, JJ commented on docs/README
> +## *Soy un pescador novel y pesco por gusto. Quiero pescar, pero no sé dónde hacerlo, y preferiría no alejarme demasiado de mi ciudad.*
Por favor, usa correctamente los formatos de Markdown. En ingeniería es importante que el formato de un documento sea correcto.

2024-02-15 08:04 UTC, JJ commented on docs/README
> +primer milestone es ennrega modelo del problema
Las frases comienzan con mayúscula, pero deberías intentar expresar aquí qué es lo que se va a entregar al cliente en el primer milestone. ¿Cómo se va a entregar ese modelo? ¿Qué parte del problema o de qué problema estamos hablando? Un milestone es una descripción de un producto que tiene que guiar a un equipo de desarrollo para resolver una serie de problemas para hacer este producto realidad.

2024-02-15 08:04 UTC, JJ commented on docs/README
> +### **Voy a usar ese herramienta una vez a la semana para _elegir sitio_ para pescar.Tiene que ser una aplicación para móvil**
En el nivel 1 hay que describir un problema, no decir cuál es la solución. Que sea una aplicación móvil u otra cosa se irá haciendo a lo largo del desarrollo.

2024-02-15 17:38 UTC, JJ reviewed
Espero que estos comentarios te ayuden a alcanzar el objetivo.

En especial, sería muy conveniente que explicaras en el documento claramente cuales son los problemas que tiene nuestro pescador. 

Trata por favor de seguir también las instrucciones en el [guión(https://jj.github.io/MPDA-IS/doc/1.Planificacion.html), por ejemplo:

> esta entrega incluirá

> Un subdirectorio docs donde se pondrá material adicional (que se tendrá que enlazar desde el README en el apartado que se esté corrigiendo en ese momento).


Entiendo que es mucha información, pero en ingeniería hay que tratar de entender bien las instrucciones que se imparten, generalmente por escrito, y seguir los requisitos al pie de la letra, o al menos de forma que se alcance el objetivo deseado.

2024-02-15 17:38 UTC, JJ commented on docs/README
> +## Soy un pescador principiante. Quiero conocer más lugares de pesca. Así como la previsión meteorológica para la ubicación seleccionada, como la temperatura y el viento. También quería poder guardar
Si usas `##` es para titulares de segundo orden. Si esto es texto normal, simplemente quita este.
Por otro lado, tienes que expresar claramente el problema como tal problema. "Quiero conocer más lugares de pesca" no es un problema, y como tal es imposible de solucionar (o se soluciona de forma trivial). El problema sería la razón por la que quiere conocer más lugares de pesca. ¿Los que conoce no le gustan? ¿Por qué no le gustan?
Sería conveniente también que expliques qué es un lugar de pesca, porque a priori no es fácil de saber.

En el momento que uses "también", ya estás dejando claro que no estás hablando de un problema, sino de soluciones que se te han ocurrido a ti a problemas no existentes o no diagnosticados. ¿Por qué quiere guardar lugares favoritos? ¿Es que no se acuerda donde pesca? ¿En qué mapa?

2024-02-15 17:38 UTC, JJ commented on docs/README
> +Primer milestone. La entrega del modelo de producto que satisface las necesidades del cliente. El equipo debe haber desarrollado un prototipo o modelo funcional que aborde las necesidades específicas
De veras que deberías mirar la lista de comprobación, porque evitaríais correcciones y entenderíais mejor qué se busca. En concreto, hay una pregunta que dice así:

> [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?

¿Crees que lo que comentas aquí, la entrega de un modelo de producto, coincide con lo dicho en el nivel 2?

Por otro lado, también te dice:

> ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?

¿Este es un milestone interno, o directamente es un milestone externo?

También, en la pregunta anterior:

> ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?

¿Crees que un modelo de producto es lo mínimo, y que se puede desarrollar directamente a partir de las historias de usuario? ¿O quizás habrá que primero entender el problema de lo que se trata, a continuación tratar de programar parte de ese problema a nivel simplemente de una función, y más adelante, 10 o 12 milestones más adelante, entregar el prototipo?

2024-02-15 18:49 UTC, Artur-Sultanov commented on docs/README
> +## *Soy un pescador novel y pesco por gusto. Quiero pescar, pero no sé dónde hacerlo, y preferiría no alejarme demasiado de mi ciudad.*
@JJ Hecho

2024-02-15 18:49 UTC, Artur-Sultanov commented on docs/README
> +### **Voy a usar ese herramienta una vez a la semana para _elegir sitio_ para pescar.Tiene que ser una aplicación para móvil**
@JJ Hecho

2024-02-15 18:51 UTC, Artur-Sultanov commented on docs/README
> +primer milestone es ennrega modelo del problema
@JJ hecho

2024-02-15 18:52 UTC, Artur-Sultanov commented on docs/README
> +## Soy un pescador principiante. Quiero conocer más lugares de pesca. Así como la previsión meteorológica para la ubicación seleccionada, como la temperatura y el viento. También quería poder guardar
@JJ Hecho

2024-02-15 19:46 UTC, JJ requested changes
Aparte de lo comentado, deberías tratar de organizar las historias de usuario y milestones en ficheros diferentes. También tendrías que tratar de identificar claramente el cliente de tu aplicación, o posibles clientes. En el [guión(https://jj.github.io/MPDA-IS/doc/1.Planificacion.html) se habla de la metodología de "personas" (puedes ver la descripción [aquí](https://www.designthinking.services/herramientas-design-thinking/metodo-persona/) o buscar la que quieras). Esta metodología trata de identificar y describir a los clientes, para poder satisfacer de la mejor forma posible sus deseos.

Esos deseos tienen que estar en la historia de usuario, que, como dice en la documentación,

> Las historias de usuario siempre expresan deseos y beneficios, están relacionadas con la lógica de negocio y están en el dominio del problema.

"Buscar" no está en el dominio del problema, no expresa más que una actividad que puede ser una solución (o no) al problema. 

Creo que antes de avanzar con las historias de usuario deberías clarificar, en el README.md principal, cuál es el problema con el que vas a trabajar y cuál es el cliente al cual vas a intentar satisfacer.

2024-02-15 19:46 UTC, JJ commented on docs/README.md
> +La entrega del modelo de producto que satisface las necesidades del cliente. El equipo debe haber desarrollado un prototipo o modelo funcional que aborde las necesidades específicas del cliente. Es f
En este milestone no estás trabajando con el "producto", sino con el problema. Tienes que entender el problema del cliente.

2024-02-15 19:46 UTC, JJ commented on docs/README.md
> +Soy un pescador principiante. No se donde ir a pescar. Quiero conocer lugares de pesca cercanos a mi localizacion.
¿El problema con el que vas a trabajar es el desconocimiento? ¿Conocer lugares de pesca no se soluciona simplemente con un buscador y poniendo "lugares de pesca"?

"Quiero conocer" es una solución al problema, no la expresión de un problema.

2024-02-21 15:47 UTC, JJ requested changes
Aparte de lo comentado, te recuerdo que es esencial que conozcas bien el problema para poder intentar resolverlo. Si no, es muy difícil que entiendas qué es lo que el cliente quiere.

2024-02-21 15:47 UTC, JJ commented on README.md
>  Soy un pescador novel y pesco por gusto. Quiero pescar, pero no sé dónde hacerlo, y preferiría no alejarme demasiado de mi ciudad.
¿Cuál es el problema? Tienes que enunciar claramente cuál es el problema y su contexto. ¿Por qué no sabe dónde hacerlo? ¿No existe esa información? ¿Qué tipo de pesca busca? ¿Seguro que hay cerca de la ciudad?

2024-02-21 15:47 UTC, JJ commented on docs/Historias de usuario.md
> +Soy un pescador principiante. No se donde ir a pescar. Quiero conocer lugares de pesca cercanos a mi localizacion.
Estás repitiendo lo que has dicho en en problema. Una historia de usuario es un documento de trabajo que tiene que proporcionar contexto suficiente para empezar a desarrollar el código. ¿Es significativo que sea principiante? ¿Un pescador avanzado no tendría ese problema o tendría otro? ¿Sólo hay esta historia de usuario?
Al final, la pregunta es: Si tu recibes este documento, ¿puedes empezar a trabajar en el código? Mira por favor lo que dice el guión:

> Las historias de usuario siempre expresan deseos y beneficios, están relacionadas con la lógica de negocio y están en el dominio del problema. 

¿Has pensado en la lógica de negocio? ¿Qué beneficio quiere encontrar del programa tu cliente?

2024-02-21 15:47 UTC, JJ commented on docs/Milestones.md
> +La entrega del modelo de problema que satisface las necesidades del cliente. El equipo debe haber desarrollado un prototipo o modelo funcional que aborde las necesidades específicas del cliente.
¿Un modelo del problema, un prototipo o un modelo funcional?

2024-02-21 15:47 UTC, JJ commented on docs/Milestones.md
> +Desarrollar un algoritmo para verificar los lugares cercanos de ubicacion indicada
¿El problema es *verificar* ? ¿Es decir, hay sitios que pueden tener características que hagan que no se pueda pescar? ¿Ves como hay que enunciar claramente el problema?

2024-02-22 16:57 UTC, JJ reviewed
Recuerda también ponerle un título (`#`) a cada uno de los ficheros.

2024-02-22 16:57 UTC, JJ commented on docs/HU_1.md
> +Soy un pescador mayor con mucha experiencia y vivo en la playa. Conozco muchos sitios de pesca pero ultimamente pesco en mismo sitio más cercano a mi casa. Por mi enfermedad no puedo pescar solo porq
OK, no veo muy claro qué beneficio puede obtener esta persona de un programa, o qué es realmente lo que busca. No es importante siempre que haya otras HUs para trabajar.

Por otro lado, por favor pon siempre un título en la primera línea del fichero; con el número de HU y el nombre del cliente.

Ten en cuenta que siempre la pregunta es ¿por qué querría esta persona usar mi programa? ¿Qué problema tiene?

2024-02-22 16:57 UTC, JJ commented on docs/HU_2.md
> +Soy un pescador novel. Vivo en la playa hace poco y no tengo muchos amigos. Pesco cuando me apetezca y mayoria del tiempo solo. Normalmente invito conocidos pero no quero ser pesado y escribir a todo
Con estas historias de usuario, da la impresión de que no es tanto buscar dónde pescar si no *con quién* pescar. ¿No sería un problema diferente? Por favor, asegúrate de que sean coherentes las historias de usuario con el problema inicial enunciado.

2024-02-22 16:57 UTC, JJ commented on docs/HU_3.md
> +Soy pescador principante y vivo en una hora de la playa. Bajo a la playa en vez de cuando con mi hija para pescar y pescado no nos interesa mucho por eso al sacar lo tiramos al mar. Bajamos para desc
Todos viven cerca de la playa. Esta HU parece un poco más cercana al problema inicial. Como te digo, no me preocupa tanto que haya otras que se alejen un poco, pero sí tendrías que tratar de numerar las historias de usuario de forma que la primera sea con la que vas a empezar a trabajar.

2024-02-22 17:03 UTC, JJ reviewed
Algunos comentarios adicionales.

2024-02-22 17:03 UTC, JJ commented on docs/HU_4.md
> +Somos una familia con dos hijos de 9 y 12 años. Madre pesca desde pequeña y bajamos a la playa un par fines de semana en mes. Es que vivimos en una hora de la playa. Normalmente elegimos sitios para
OK, parece también una historia que encaja con el problema que has descrito anteriormente; considera numerarla entre las primeras, por delante de las anteriores.

2024-02-22 17:03 UTC, JJ commented on docs/Milestone_0.md
> +La entrega del modelo de problema que satisface las necesidades del cliente. El equipo debe haber desarrollado un prototipo o modelo funcional que aborde las necesidades específicas del cliente.
En esta etapa todavía no hay suficiente información para hacer un prototipo, es sólo un modelo del problema en forma de código.
Además, parece que habría varios clientes, tantos como historias de usuario con las que vayas a trabajar; también tendrás que indicar con precisión cuales son las historias de usuario de las 4 que has indicado.

2024-02-22 17:23 UTC, JJ commented on docs/Milestone_0.md
> +La entrega del modelo de problema que satisface las necesidades del cliente.
Recuerda especificar con qué historias de usuario vas a trabajar.

2024-02-22 18:34 UTC, JJ approved these changes
Lo voy a dar por aprobado, salvo que deberías especificar mejor el milestone 1. Como ahora sólo vamos a trabajar con el 0, puedes hacerlo antes de fusionar el PR o más adelante cuando lo pases a GitHub. Recuerda mirar en el guión de este nivel lo que hay que hacer: esencialmente, trasladar las HUs a issues de GitHub y los milestones a milestones también.

2024-02-22 18:34 UTC, JJ commented on docs/Milestone_1.md
> +Desarrollar Producto Mínimo Viable segun modelo en milestone_0
Por favor, especifica qué es el producto mínimamente viable. ¿Será llevar a cabo las funciones necesarias que usen el modelo desarrollado en el anterior?

2024-02-22 19:00 UTC, merged